import Provider from "@/redux/Provider";
import "./layout.scss";

export const metadata = {
	title: "Rent Your Yacht",
	description: "Generated by Next.js",
};

const RootLayout = ({ children }) => {
	return (
		<html>
			<head>
				<link rel="icon" href="/sail-boat.svg" sizes="any" />
			</head>
			<body>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
};

export default RootLayout;
