import "../styles/globals.css";
import Provider from "@/redux/Provider";
import IMAGE from "../../public/links";
import "./layout.scss";

export const metadata = {
	title: "Rent Your Yacht",
	description: "Generated by Next.js",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html>
			<head>
				<link rel="icon" href={IMAGE.svg.sailBoat} sizes="any" />
			</head>
			<body>
				<Provider>
					<main>{children}</main>
				</Provider>
			</body>
		</html>
	);
};

export default RootLayout;
