import "./layout.scss";

export const metadata = {
	title: "Rent Your Yacht",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html>
			<head>
				<link rel="icon" href="/sail-boat.svg" sizes="any" />
			</head>
			<body>{children}</body>
		</html>
	);
}
