export const metadata = {
	title: "Rent Your Yacht",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html>
			<body>{children}</body>
		</html>
	);
}
