enum Captions {
  APP_NAME = 'Boatify',

  PAGE_NAME_HARBOURS = 'Porty',
  PAGE_NAME_BOATS = 'Łodzie',
  PAGE_NAME_LAST_MINUTE = 'Gorące Okazje',
  PAGE_NAME_CONTACT = 'Kontakt',

  PAGE_NAME_MY_PROFILE = 'Mój Profil',
  PAGE_NAME_MY_RESERVATIONS = 'Moje Rezerwacje',
  PAGE_NAME_MY_BOATS = 'Moje Łodzie',
  LOGOUT = 'Wyloguj',

  MAP_LINK_TEXT1 = 'Wykorzystaj mapę portów aby zaplanować idealne wakacje',
  MAP_LINK_TEXT2 = 'Otwórz mapę',
  MAP_LINK_IMAGE_ALT = 'Mapa',
  X = 'X',
  EqualsSign = '=',
  Type = 'Typ: ',
  PricePerDay = 'Cena za dzień: ',
  PLN = 'PLN',
  Step1Label = 'Wybrana łódź',
  Step2Label = 'Wybierz okres',
  Step3Label = 'Podsumowanie rezerwacji',
  Step4Label = 'Płatność',
  Next = 'Dalej',
  PROFILE_EMAIL = 'Email: ',
  PROFILE_ROLE = 'Rola: ',
  PROFILE_DATE_OF_BIRTH = 'Data urodzenia: ',
  BOAT_NAME = 'Nazwa: ',
  BOAT_DESCRIPTION = 'Opis: ',
  BOAT_MODEL = 'Model: ',
  BOAT_TYPE = 'Typ: ',
  BOAT_PRICE_PER_DAY = 'Cena za dzień: ',
  BOAT_PASSENGERS_NUMBER = 'Liczba pasażerów',
  BOAT_CURRENT_LOCATION = 'Obecna lokalizacja: ',
  RESERVATION = 'Rezerwacja',
  RESERVATION_TOTAL_PRICE = 'Cena w sumie: ',
  RESERVATION_START_DATE = 'Dzień rozpoczęcia: ',
  RESERVATION_END_DATE = 'Dzień zakończenia: ',
  RESERVATION_STATUS = 'Status: ',
  SELF_RESERVATION = 'Rezerwacja własna na wybrane dni: ',
  MY_RESERVATIONS = 'Moje rezerwacje',
  MY_BOATS_RESERVATIONS = 'Rezerwacje moich łodzi',
  HERO_HEADER = 'Żegluj z nami',
  HERO_HEADER_DESCRIPTION = 'Znajdź swoją wymarzoną lódź na rejs',
  FEATURED1 = 'Zaloguj się',
  FEATURED2 = 'Zarejestruj się',
  FEATURED3 = 'Przeglądaj',
  CONTACT_NAME = 'Imię',
  CONTACT_SUBJECT = 'Temat',
  CONTACT_EMAIL = 'E-mail',
  CONTACT_MESSAGE = 'Wiadomość',
  CONTACT_MESSAGE_TYPE_HERE = 'Pisz...',
  CONTACT_SEND_MESSAGE = 'Wyślij',
}

export default Captions;
