enum Captions {
  APP_NAME = 'Boatify',
  PAGE_NAME_HARBOURS = 'Porty',
  PAGE_NAME_BOATS = 'Łodie',
  PAGE_NAME_LAST_MINUTE = 'Gorące Okazje',
  PAGE_NAME_CONTACT = 'Kontakt',
  MAP_LINK_TEXT1 = 'Wykorzystaj mapę portów aby zaplanować idealne wakacje',
  MAP_LINK_TEXT2 = 'Otwórz mapę',
  MAP_LINK_IMAGE_ALT = 'Mapa',
  X = 'X',
  EqualsSign = '=',
  Type = 'Typ: ',
  PricePerDay = 'Cena za dzień: ',
  PLN = 'PLN',
  Step1Label = 'Wybrana łódź',
  Step2Label = 'Wybierz okres',
  Step3Label = 'Podsumowanie rezerwacji',
  Step4Label = 'Płatność',
  Next = 'Dalej',
  PROFILE_EMAIL = 'Email: ',
  PROFILE_ROLE = 'Rola: ',
  PROFILE_DATE_OF_BIRTH = 'Data urodzenia: ',
  BOAT_NAME = 'Nazwa: ',
  BOAT_DESCRIPTION = 'Opis: ',
  BOAT_MODEL = 'Model: ',
  BOAT_TYPE = 'Typ: ',
  BOAT_PRICE_PER_DAY = 'Cena za dzień: ',
  BOAT_PASSENGERS_NUMBER = 'Liczba pasażerów',
  BOAT_CURRENT_LOCATION = 'Obecna lokalizacja: ',
  RESERVATION = 'Rezerwacja',
  RESERVATION_TOTAL_PRICE = 'Cena w sumie: ',
  RESERVATION_START_DATE = 'Dzień rozpoczęcia: ',
  RESERVATION_END_DATE = 'Dzień zakończenia: ',
  RESERVATION_STATUS = 'Status: ',
  SELF_RESERVATION = 'Rezerwacja własna na wybrane dni: ',
  MY_RESERVATIONS = 'Moje rezerwacje',
  HERO_HEADER = 'Żegluj z nami',
  HERO_HEADER_DESCRIPTION = 'Znajdź swoją wymarzoną lódź na rejs',
}

export default Captions;
