enum Captions {
  APP_NAME = 'Boatify',
  PAGE_NAME_HARBOURS = 'Harbours',
  PAGE_NAME_BOATS = 'Boats',
  PAGE_NAME_LAST_MINUTE = 'Last Minute',
  PAGE_NAME_SHOP = 'Shop',
  PAGE_NAME_CONTACT = 'Contact',
  MAP_LINK_TEXT1 = 'Wykorzystaj mapę portów aby zaplanować idealne wakacje',
  MAP_LINK_TEXT2 = 'Otwórz mapę',
  MAP_LINK_IMAGE_ALT = 'Map',
  X = 'X',
  EqualsSign = '=',
  Type = 'Type: ',
  PricePerDay = 'Price per Day: ',
  PLN = 'PLN',
  Step1Label = 'Chosen Boat',
  Step2Label = 'Select Time',
  Step3Label = 'Reservation Summary',
  Step4Label = 'Payment',
  Next = 'Next',
  PROFILE_EMAIL = 'Email: ',
  PROFILE_ROLE = 'Role: ',
  PROFILE_DATE_OF_BIRTH = 'Date of Birth: ',
  BOAT_NAME = 'Name: ',
  BOAT_DESCRIPTION = 'Description: ',
  BOAT_MODEL = 'Model: ',
  BOAT_TYPE = 'Type: ',
  BOAT_PRICE_PER_DAY = 'Price per day: ',
  BOAT_CURRENT_LOCATION = 'Current location: ',
}

export default Captions;
